# Generated by Django 3.0.7 on 2020-07-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocomplete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocompleterecord',
            name='updated_at',
        ),
    ]
