# Generated by Django 3.0.7 on 2020-07-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocomplete', '0002_remove_autocompleterecord_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autocompleterecord',
            name='created_at',
        ),
    ]
