FROM art-dash-server:base

# This build is meant to be based on an existing build and
# update just doozer, elliott, and art-dash.

# Use same non-root user from the initial install
ARG USERNAME=dev
# On Linux, replace with your actual UID, GID if not the default 1000
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Since art-dash-server:base is set as dev user, we need to switch back to root
USER 0
# install default configs
COPY container/doozer-settings.yaml /home/"$USERNAME"/.config/doozer/settings.yaml
COPY container/elliott-settings.yaml /home/"$USERNAME"/.config/elliott/settings.yaml

# Switching back to default user
USER "$USER_UID"

WORKDIR /workspaces/art-dash

# Update uv
RUN uv self update

COPY requirements.txt ./
RUN uv pip install --upgrade -r requirements.txt \
    && rm requirements.txt  # We need to manually remove since we copied using COPY

# Clone art-tools and install
RUN cd art-tools \
    && git pull \
    && pip3 install -e artcommon/ -e doozer/ -e elliott/ -e pyartcd/ -e ocp-build-data-validator/

COPY . .
