FROM art-dash-server:base

# This build is meant to be based on an existing build and
# update just doozer, elliott, and art-dash.

# Use same non-root user from the initial install
ARG USERNAME=dev
# On Linux, replace with your actual UID, GID if not the default 1000
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Since art-dash-server:base is set as dev user, we need to switch back to root
USER 0
# install default configs
COPY . /tmp/art-dash
RUN cp /tmp/art-dash/container/doozer-settings.yaml /home/"$USERNAME"/.config/doozer/settings.yaml \
 && cp /tmp/art-dash/container/elliott-settings.yaml /home/"$USERNAME"/.config/elliott/settings.yaml \
 && rm -rf /tmp/art-dash

# Switching back to default user
USER "$USER_UID"

WORKDIR /workspaces
# Upadate pip
RUN python3 -m pip install --upgrade pip
COPY requirements.txt ./
RUN pip3 install --upgrade -r requirements.txt

# Update art-tools and run the install script
RUN cd art-tools \
    && git pull \
    && ./install.sh

WORKDIR /workspaces/art-dash

COPY . .
