# # Generated by Django 3.0.7 on 2020-07-27 19:23
#
# import build_health.models
# from django.db import migrations_old, models
# import django.utils.timezone
#
#
# class Migration(migrations_old.Migration):
#
#     initial = True
#
#     dependencies = [
#     ]
#
#     operations = [
#         migrations_old.CreateModel(
#             name='Build',
#             fields=[
#                 ('updated_at', build_health.models.UnixTimestampField(auto_created=True, null=True)),
#                 ('created_at', build_health.models.UnixTimestampField(auto_created=True, null=True)),
#                 ('log_build_id', models.AutoField(primary_key=True, serialize=False)),
#                 ('request_id', models.BigIntegerField(blank=True, null=True)),
#                 ('build_id', models.CharField(blank=True, max_length=300, null=True)),
#                 ('fault_code', models.CharField(blank=True, max_length=300, null=True)),
#                 ('image_shas', models.CharField(blank=True, max_length=2000, null=True)),
#                 ('task_id', models.CharField(blank=True, max_length=100, null=True)),
#                 ('task_state', models.CharField(blank=True, max_length=100, null=True)),
#                 ('build_0_id', models.CharField(blank=True, max_length=300, null=True)),
#                 ('build_0_name', models.CharField(blank=True, max_length=300, null=True)),
#                 ('build_0_nvr', models.CharField(blank=True, max_length=500, null=True)),
#                 ('build_0_package_id', models.CharField(blank=True, max_length=300, null=True)),
#                 ('build_0_release', models.CharField(blank=True, max_length=300, null=True)),
#                 ('build_0_source', models.CharField(blank=True, max_length=300, null=True)),
#                 ('build_0_version', models.CharField(blank=True, max_length=300, null=True)),
#                 ('build_iso_time', models.DateTimeField(blank=True, null=True)),
#                 ('build_unix_time', models.FloatField(blank=True, null=True)),
#                 ('dg_commit', models.CharField(blank=True, max_length=300, null=True)),
#                 ('dg_name', models.CharField(blank=True, max_length=300, null=True)),
#                 ('dg_namespace', models.CharField(blank=True, max_length=300, null=True)),
#                 ('dg_qualified_key', models.CharField(blank=True, max_length=300, null=True)),
#                 ('dg_qualified_name', models.CharField(blank=True, max_length=300, null=True)),
#                 ('group', models.CharField(blank=True, max_length=300, null=True)),
#                 ('incomplete', models.CharField(blank=True, max_length=300, null=True)),
#                 ('jenkins_build_number', models.CharField(blank=True, max_length=300, null=True)),
#                 ('jenkins_build_url', models.CharField(blank=True, max_length=300, null=True)),
#                 ('jenkins_job_name', models.CharField(blank=True, max_length=300, null=True)),
#                 ('jenkins_job_url', models.CharField(blank=True, max_length=300, null=True)),
#                 ('jenkins_node_name', models.CharField(blank=True, max_length=300, null=True)),
#                 ('label_com_redhat_component', models.CharField(blank=True, max_length=300, null=True)),
#                 ('label_io_openshift_build_commit_id', models.CharField(blank=True, max_length=300, null=True)),
#                 ('build_commit_url_github', models.CharField(blank=True, max_length=300, null=True)),
#                 ('label_io_openshift_build_source_location', models.CharField(blank=True, max_length=300, null=True)),
#                 ('label_io_openshift_maintainer_product', models.CharField(blank=True, max_length=300, null=True)),
#                 ('label_io_openshift_tags', models.CharField(blank=True, max_length=300, null=True)),
#                 ('label_name', models.CharField(blank=True, max_length=300, null=True)),
#                 ('label_version', models.CharField(blank=True, max_length=300, null=True)),
#                 ('iso_time', models.DateTimeField(blank=True, null=True)),
#                 ('unix_time', models.FloatField(blank=True, null=True)),
#             ],
#             options={
#                 'db_table': 'log_build',
#             },
#         ),
#         migrations_old.CreateModel(
#             name='DailyBuildReport',
#             fields=[
#                 ('updated_at', build_health.models.UnixTimestampField(auto_created=True, null=True)),
#                 ('created_at', build_health.models.UnixTimestampField(auto_created=True, null=True)),
#                 ('log_build_daily_summary_id', models.AutoField(primary_key=True, serialize=False)),
#                 ('fault_code', models.CharField(max_length=300)),
#                 ('date', models.DateField()),
#                 ('dg_name', models.CharField(max_length=300)),
#                 ('label_name', models.CharField(max_length=300)),
#                 ('label_version', models.CharField(max_length=300)),
#                 ('count', models.BigIntegerField()),
#                 ('request_id', models.BigIntegerField(blank=True, null=True)),
#             ],
#             options={
#                 'db_table': 'log_build_daily_summary',
#             },
#         ),
#         migrations_old.CreateModel(
#             name='HealthRequests',
#             fields=[
#                 ('request_id', models.AutoField(primary_key=True, serialize=False)),
#                 ('type', models.CharField(choices=[('d', 'daily'), ('h', 'hourly')], max_length=20)),
#                 ('start_time', models.DateTimeField()),
#                 ('end_time', models.DateTimeField()),
#                 ('status', models.BooleanField(default=False)),
#                 ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
#                 ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
#             ],
#             options={
#                 'db_table': 'log_import_requests',
#             },
#         ),
#     ]
