# # Generated by Django 3.0.7 on 2020-07-27 20:40
#
# from django.db import migrations_old, models
#
#
# class Migration(migrations_old.Migration):
#
#     dependencies = [
#         ('build_health', '0001_initial'),
#     ]
#
#     operations = [
#         migrations_old.AlterField(
#             model_name='dailybuildreport',
#             name='dg_name',
#             field=models.CharField(blank=True, max_length=300, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='dailybuildreport',
#             name='fault_code',
#             field=models.CharField(blank=True, max_length=300, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='dailybuildreport',
#             name='label_name',
#             field=models.CharField(blank=True, max_length=300, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='dailybuildreport',
#             name='label_version',
#             field=models.CharField(blank=True, max_length=300, null=True),
#         ),
#     ]
