# # Generated by Django 3.0.7 on 2021-01-20 03:37
#
# from django.db import migrations_old, models
#
#
# class Migration(migrations_old.Migration):
#
#     dependencies = [
#         ('build_health', '0002_auto_20200727_2040'),
#     ]
#
#     operations = [
#         migrations_old.RenameField(
#             model_name='build',
#             old_name='build_iso_time',
#             new_name='build_time_iso',
#         ),
#         migrations_old.RenameField(
#             model_name='build',
#             old_name='log_build_id',
#             new_name='log_log_build_id',
#         ),
#         migrations_old.RemoveField(
#             model_name='build',
#             name='build_0_id',
#         ),
#         migrations_old.RemoveField(
#             model_name='build',
#             name='build_unix_time',
#         ),
#         migrations_old.RemoveField(
#             model_name='build',
#             name='image_shas',
#         ),
#         migrations_old.RemoveField(
#             model_name='build',
#             name='request_id',
#         ),
#         migrations_old.RemoveField(
#             model_name='build',
#             name='task_state',
#         ),
#         migrations_old.RemoveField(
#             model_name='build',
#             name='unix_time',
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='brew_build_ids',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='brew_image_shas',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='brew_task_state',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='build_time_unix',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_KUBE_GIT_COMMIT',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_KUBE_GIT_MAJOR',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_KUBE_GIT_MINOR',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_KUBE_GIT_TREE_STATE',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_KUBE_GIT_VERSION',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_OS_GIT_COMMIT',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_OS_GIT_MAJOR',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_OS_GIT_MINOR',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_OS_GIT_PATCH',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_OS_GIT_TREE_STATE',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='env_OS_GIT_VERSION',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='label_io_openshift_build_versions',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='label_io_openshift_expose_services',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='label_io_openshift_maintainer_component',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='label_io_openshift_maintainer_subcomponent',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='label_io_openshift_release_operator',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='label_io_openshift_s2i_scripts_url',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='label_release',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='runtime_user',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='runtime_uuid',
#             field=models.FloatField(blank=True, null=True),
#         ),
#         migrations_old.AddField(
#             model_name='build',
#             name='time_unix',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_0_name',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_0_nvr',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_0_package_id',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_0_release',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_0_source',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_0_version',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_commit_url_github',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='build_id',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='dg_commit',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='dg_name',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='dg_namespace',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='dg_qualified_key',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='dg_qualified_name',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='fault_code',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='group',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='incomplete',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='jenkins_build_number',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='jenkins_build_url',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='jenkins_job_name',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='jenkins_job_url',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='jenkins_node_name',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='label_com_redhat_component',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='label_io_openshift_build_commit_id',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='label_io_openshift_build_source_location',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='label_io_openshift_maintainer_product',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='label_io_openshift_tags',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='label_name',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='label_version',
#             field=models.CharField(blank=True, max_length=1000, null=True),
#         ),
#         migrations_old.AlterField(
#             model_name='build',
#             name='task_id',
#             field=models.BigIntegerField(blank=True, null=True),
#         ),
#     ]
