# Generated by Django 3.0.7 on 2020-07-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenShiftCurrentAdvisory',
            fields=[
                ('log_openshift_release_advisory_id', models.AutoField(primary_key=True, serialize=False)),
                ('openshift_version', models.CharField(max_length=50)),
                ('advisory_type', models.CharField(max_length=100)),
                ('current_advisory_id', models.CharField(max_length=20)),
                ('previous_advisory_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'log_openshift_release_advisory',
            },
        ),
    ]
