# Generated by Django 3.0.7 on 2022-08-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenShiftCurrentAdvisory',
            fields=[
                ('log_openshift_release_advisory_id', models.AutoField(primary_key=True, serialize=False)),
                ('openshift_version', models.CharField(max_length=50)),
                ('brew_event', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'log_openshift_release_advisory',
                'managed': True,
            },
        ),
    ]
