# Generated by Django 3.0.7 on 2020-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocp_build_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openshiftcurrentadvisory',
            name='current_advisory_sha',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='openshiftcurrentadvisory',
            name='previous_advisory_sha',
            field=models.CharField(default='', max_length=200),
        ),
    ]
