# Generated by Django 3.0.7 on 2020-06-23 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRequests',
            fields=[
                ('request_id', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('d', 'daily'), ('h', 'hourly')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 6, 23, 18, 34, 13, 84704, tzinfo=utc))),
            ],
        ),
    ]
