# Generated by Django 3.0.7 on 2020-06-23 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrequests',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 20, 20, 20, 420442, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='healthrequests',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
