# Generated by Django 3.0.7 on 2020-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0002_auto_20200623_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrequests',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
