# Generated by Django 3.0.7 on 2020-06-23 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0004_auto_20200623_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrequests',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='healthrequests',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
