# Generated by Django 3.0.7 on 2020-06-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0005_auto_20200623_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('build_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('build_id', models.BigIntegerField(blank=True, null=True)),
                ('fault_code', models.CharField(max_length=300)),
                ('task_id', models.BigIntegerField(blank=True, null=True)),
                ('task_state', models.CharField(blank=True, max_length=20, null=True)),
                ('iso_time', models.DateTimeField()),
                ('unix_time', models.FloatField()),
                ('dg_commit', models.CharField(max_length=300)),
                ('dg_name', models.CharField(max_length=300)),
                ('dg_namespace', models.CharField(max_length=300)),
                ('group', models.CharField(max_length=300)),
                ('jenkins_build_number', models.BigIntegerField()),
                ('jenkins_build_url', models.URLField()),
                ('jenkins_job_name', models.CharField(max_length=300)),
                ('jenkins_job_url', models.URLField()),
                ('label_name', models.CharField(max_length=300)),
                ('label_version', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'log_build',
            },
        ),
    ]
