# Generated by Django 3.0.7 on 2020-06-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0007_auto_20200624_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='request_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
