# Generated by Django 3.0.7 on 2020-06-24 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0008_build_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBuildReport',
            fields=[
                ('log_build_daily_summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('fault_code', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('dg_name', models.CharField(max_length=300)),
                ('label_name', models.CharField(max_length=300)),
                ('label_version', models.CharField(max_length=300)),
                ('count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'log_build_daily_summary',
            },
        ),
        migrations.AlterField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='build',
            name='updated_at',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
