# Generated by Django 3.0.7 on 2020-06-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0009_auto_20200624_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybuildreport',
            name='request_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
