# Generated by Django 3.0.7 on 2020-06-24 06:13

import build_health.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0010_dailybuildreport_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybuildreport',
            name='created_at',
            field=build_health.models.UnixTimestampField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailybuildreport',
            name='updated_at',
            field=build_health.models.UnixTimestampField(auto_created=True, null=True),
        ),
    ]
