# Generated by Django 3.0.7 on 2020-06-24 20:40

import build_health.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('build_health', '0011_auto_20200624_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='created_at',
            field=build_health.models.UnixTimestampField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='updated_at',
            field=build_health.models.UnixTimestampField(auto_created=True, null=True),
        ),
    ]
