# Generated by Django 3.0.7 on 2020-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
