# Generated by Django 3.0.7 on 2020-10-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reports', '0002_auto_20200930_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
